---
language: node_js
node_js:
  - 7
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  repo: scastiel/blog.castiel.me
  target_branch: gh-pages
  email: sebastien@castiel.me
  name: Sébastien Castiel
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: blog.castiel.me
  on:
    branch: master